import { Building, Globe2, Shield, Trophy, Zap, Factory, Cpu, Database, Cloud, Smartphone, Monitor, Package, Linkedin, Crown, Star } from 'lucide-react'

export const TOP_MNC_COMPANIES = [
    {
        id: 1,
        name: "Microsoft",
        logo: "/logos/microsoft.png",
        brandColor: "bg-gradient-to-br from-blue-600 to-blue-800",
        icon: Monitor,
        primaryColor: "from-blue-600 to-blue-800",
        lightColor: "bg-blue-50",
        textColor: "text-blue-700",
        description: "Leading technology company empowering digital transformation worldwide.",
        rating: 4.7,
        reviews: 2847,
        openJobs: 145,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Software", "Cloud Computing", "AI", "Gaming", "Hardware"],
        employees: "181,000+",
        headquarters: "Redmond, WA"
    },
    {
        id: 2,
        name: "Google",
        logo: "/logos/google.png",
        brandColor: "bg-gradient-to-br from-red-500 to-yellow-500",
        icon: Cloud,
        primaryColor: "from-red-500 to-yellow-500",
        lightColor: "bg-yellow-50",
        textColor: "text-yellow-700",
        description: "Global technology leader organizing world's information and making it universally accessible.",
        rating: 4.6,
        reviews: 3256,
        openJobs: 189,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Search", "AI", "Cloud", "Advertising", "Hardware"],
        employees: "139,995+",
        headquarters: "Mountain View, CA"
    },
    {
        id: 3,
        name: "Amazon",
        logo: "/logos/amazon.png",
        brandColor: "bg-gradient-to-br from-orange-500 to-yellow-600",
        icon: Package,
        primaryColor: "from-orange-500 to-yellow-600",
        lightColor: "bg-orange-50",
        textColor: "text-orange-700",
        description: "E-commerce and cloud computing giant delivering innovation to customers globally.",
        rating: 4.4,
        reviews: 1987,
        openJobs: 267,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["E-commerce", "Cloud Computing", "Logistics", "Digital Streaming"],
        employees: "1,298,000+",
        headquarters: "Seattle, WA"
    },
    {
        id: 4,
        name: "Apple",
        logo: "/logos/apple.png",
        brandColor: "bg-gradient-to-br from-gray-700 to-gray-900",
        icon: Smartphone,
        primaryColor: "from-gray-700 to-gray-900",
        lightColor: "bg-gray-50",
        textColor: "text-gray-700",
        description: "Innovative technology company designing revolutionary products and experiences.",
        rating: 4.8,
        reviews: 1543,
        openJobs: 98,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Consumer Electronics", "Software", "Services"],
        employees: "147,000+",
        headquarters: "Cupertino, CA"
    },
    {
        id: 5,
        name: "IBM",
        logo: "/logos/ibm.png",
        brandColor: "bg-gradient-to-br from-blue-700 to-blue-900",
        icon: Database,
        primaryColor: "from-blue-700 to-blue-900",
        lightColor: "bg-blue-50",
        textColor: "text-blue-700",
        description: "Enterprise technology and consulting company driving digital transformation.",
        rating: 4.3,
        reviews: 987,
        openJobs: 156,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Cloud", "AI", "Consulting", "Enterprise Software"],
        employees: "282,100+",
        headquarters: "Armonk, NY"
    },
    {
        id: 6,
        name: "Meta",
        logo: "/logos/meta.png",
        brandColor: "bg-gradient-to-br from-blue-600 to-purple-600",
        icon: Globe2,
        primaryColor: "from-blue-600 to-purple-600",
        lightColor: "bg-purple-50",
        textColor: "text-purple-700",
        description: "Building social connections and the metaverse for global community.",
        rating: 4.5,
        reviews: 1876,
        openJobs: 134,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Social Media", "VR/AR", "AI", "Messaging"],
        employees: "71,970+",
        headquarters: "Menlo Park, CA"
    },
    {
        id: 7,
        name: "Tesla",
        logo: "/logos/tesla.png",
        brandColor: "bg-gradient-to-br from-red-600 to-red-800",
        icon: Zap,
        primaryColor: "from-red-600 to-red-800",
        lightColor: "bg-red-50",
        textColor: "text-red-700",
        description: "Accelerating sustainable energy and electric vehicle innovation worldwide.",
        rating: 4.6,
        reviews: 1234,
        openJobs: 87,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Automotive", "Energy", "AI", "Manufacturing"],
        employees: "110,000+",
        headquarters: "Austin, TX"
    },
    {
        id: 8,
        name: "Oracle",
        logo: "/logos/oracle.png",
        brandColor: "bg-gradient-to-br from-red-700 to-orange-700",
        icon: Database,
        primaryColor: "from-red-700 to-orange-700",
        lightColor: "bg-red-50",
        textColor: "text-red-700",
        description: "Enterprise software company powering business innovation globally.",
        rating: 4.2,
        reviews: 876,
        openJobs: 112,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Database", "Cloud", "Enterprise Software", "ERP"],
        employees: "143,000+",
        headquarters: "Austin, TX"
    },
    {
        id: 9,
        name: "Samsung",
        logo: "/logos/samsung.png",
        brandColor: "bg-gradient-to-br from-blue-600 to-blue-800",
        icon: Smartphone,
        primaryColor: "from-blue-600 to-blue-800",
        lightColor: "bg-blue-50",
        textColor: "text-blue-700",
        description: "Global technology leader in electronics, mobile devices, and home appliances.",
        rating: 4.4,
        reviews: 1456,
        openJobs: 98,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Electronics", "Mobile", "Semiconductors", "Home Appliances"],
        employees: "267,937+",
        headquarters: "Suwon, South Korea"
    },
    {
        id: 10,
        name: "Intel",
        logo: "/logos/intel.png",
        brandColor: "bg-gradient-to-br from-blue-700 to-blue-900",
        icon: Cpu,
        primaryColor: "from-blue-700 to-blue-900",
        lightColor: "bg-blue-50",
        textColor: "text-blue-700",
        description: "Semiconductor and computing innovation leader powering digital world.",
        rating: 4.3,
        reviews: 1098,
        openJobs: 76,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Semiconductors", "Computing", "AI", "5G"],
        employees: "131,900+",
        headquarters: "Santa Clara, CA"
    },
    {
        id: 11,
        name: "Cisco",
        logo: "/logos/cisco.png",
        brandColor: "bg-gradient-to-br from-blue-600 to-blue-800",
        icon: Shield,
        primaryColor: "from-blue-600 to-blue-800",
        lightColor: "bg-blue-50",
        textColor: "text-blue-700",
        description: "Networking and cybersecurity solutions for connected world.",
        rating: 4.1,
        reviews: 765,
        openJobs: 89,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Networking", "Cybersecurity", "Collaboration", "IoT"],
        employees: "79,500+",
        headquarters: "San Jose, CA"
    },
    {
        id: 12,
        name: "Adobe",
        logo: "/logos/adobe.png",
        brandColor: "bg-gradient-to-br from-red-600 to-red-800",
        icon: Star,
        primaryColor: "from-red-600 to-red-800",
        lightColor: "bg-red-50",
        textColor: "text-red-700",
        description: "Digital experience and creative software empowering content creation.",
        rating: 4.5,
        reviews: 1234,
        openJobs: 67,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        industries: ["Creative Software", "Digital Marketing", "Analytics", "Cloud"],
        employees: "26,127+",
        headquarters: "San Jose, CA"
    }
];

export const JOBS = [
    {
        id: 1,
        title: "Senior Cloud Engineer",
        company: "Microsoft",
        location: "Redmond, WA",
        type: "Full-time",
        experience: "5+ years",
        salary: "$140k - $180k",
        department: "Engineering",
        workStyle: "Hybrid",
        postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        description: "Join Microsoft's Azure cloud engineering team to build scalable cloud solutions that power millions of businesses worldwide. You'll work on cutting-edge cloud technologies and services that are transforming the digital landscape.",
        responsibilities: [
            "Design and implement scalable cloud infrastructure solutions on Microsoft Azure",
            "Develop and maintain cloud-native applications using microservices architecture",
            "Optimize cloud performance and implement cost-effective solutions",
            "Collaborate with product teams to define cloud architecture requirements",
            "Ensure security compliance and implement best practices for cloud security",
            "Mentor junior engineers and conduct technical design reviews",
            "Stay current with emerging cloud technologies and industry trends"
        ],
        requirements: [
            "5+ years of experience in cloud engineering or related field",
            "Strong experience with Microsoft Azure services and architecture",
            "Proficiency in infrastructure as code (Terraform, ARM templates)",
            "Experience with containerization (Docker, Kubernetes) and orchestration",
            "Knowledge of networking protocols and security best practices",
            "Bachelor's degree in Computer Science or related field",
            "Microsoft certifications (Azure Solutions Architect, etc.) preferred"
        ],
        benefits: [
            "Competitive salary with performance bonuses and stock options",
            "Comprehensive health, dental, and vision insurance for family",
            "Flexible work arrangements with hybrid options",
            "$10,000 annual professional development budget",
            "Generous 401(k) matching and employee stock purchase plan",
            "Unlimited paid time off and parental leave",
            "Free Microsoft software and Surface device discount",
            "On-site fitness centers and wellness programs",
            "Access to Microsoft internal learning platforms and mentorship"
        ],
        skills: ["Azure", "Kubernetes", "Terraform", "Docker", "PowerShell", "Python", "DevOps"],
        companyDescription: "Microsoft is a leading technology company empowering digital transformation worldwide. We build innovative solutions that help businesses and individuals achieve more through the power of technology.",
        logo: "/logos/microsoft.png",
        featured: true,
        isNew: false,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.7,
        reviews: 2847,
        applicants: 89,
        contactPerson: "Sarah Johnson",
        contactEmail: "careers@microsoft.com",
        contactPhone: "+1 (425) 882-8080",
        companySize: "181,000+",
        industry: "Technology"
    },
    {
        id: 2,
        title: "AI Research Scientist",
        company: "Google",
        location: "Mountain View, CA",
        type: "Full-time",
        experience: "3-5 years",
        salary: "$160k - $220k",
        department: "Engineering",
        workStyle: "Hybrid",
        postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        description: "Join Google's AI research team to advance artificial intelligence and machine learning. You'll work on groundbreaking projects that impact billions of users globally and shape the future of technology.",
        responsibilities: [
            "Conduct cutting-edge research in artificial intelligence and machine learning",
            "Develop novel algorithms and models for large-scale applications",
            "Collaborate with product teams to integrate AI into Google products",
            "Publish research findings in top-tier conferences and journals",
            "Mentor junior researchers and contribute to team knowledge sharing",
            "Stay current with latest advancements in AI and deep learning"
        ],
        requirements: [
            "PhD or Master's degree in Computer Science, Mathematics, or related field",
            "3+ years of experience in AI/ML research or development",
            "Strong programming skills in Python, TensorFlow, or PyTorch",
            "Published research in reputable AI/ML conferences",
            "Experience with large-scale distributed systems and data processing",
            "Strong mathematical foundation and analytical thinking skills",
            "Excellent communication and collaboration abilities"
        ],
        benefits: [
            "Competitive salary with performance bonuses and equity",
            "Comprehensive health benefits including mental health coverage",
            "Flexible work arrangements with hybrid options",
            "$15,000 annual conference and research budget",
            "401(k) matching with generous company contribution",
            "Unlimited paid time off and sabbatical options",
            "Free meals, snacks, and on-site wellness facilities",
            "Access to cutting-edge AI research and computing resources",
            "Opportunities for patent participation and technical leadership"
        ],
        skills: ["Python", "TensorFlow", "PyTorch", "Deep Learning", "NLP", "Computer Vision", "Research"],
        companyDescription: "Google is a global technology leader organizing world's information and making it universally accessible. We're committed to innovation and solving complex problems with cutting-edge technology.",
        logo: "/logos/google.png",
        featured: true,
        isNew: true,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.6,
        reviews: 3256,
        applicants: 156,
        contactPerson: "Dr. Michael Chen",
        contactEmail: "careers@google.com",
        contactPhone: "+1 (650) 253-0000",
        companySize: "139,995+",
        industry: "Technology"
    },
    {
        id: 3,
        title: "Senior Solutions Architect",
        company: "Amazon",
        location: "Seattle, WA",
        type: "Full-time",
        experience: "7+ years",
        salary: "$150k - $200k",
        department: "Engineering",
        workStyle: "Hybrid",
        postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        description: "Lead architectural design for Amazon's global e-commerce and cloud platforms. You'll shape the technical direction of systems serving millions of customers worldwide.",
        responsibilities: [
            "Design scalable and resilient system architectures for Amazon Web Services",
            "Lead technical decisions for high-traffic e-commerce platforms",
            "Evaluate and recommend emerging technologies for Amazon's tech stack",
            "Mentor senior engineers and establish architectural best practices",
            "Collaborate with product teams to align technical solutions with business needs",
            "Ensure security, performance, and reliability of Amazon systems",
            "Present architectural proposals to executive leadership"
        ],
        requirements: [
            "7+ years of experience in software architecture or related field",
            "Experience with large-scale distributed systems and microservices",
            "Strong knowledge of cloud platforms (AWS, Azure, GCP)",
            "Expertise in system design, scalability, and performance optimization",
            "Experience with DevOps practices and CI/CD pipelines",
            "Bachelor's degree in Computer Science or Engineering",
            "Excellent leadership and communication skills"
        ],
        benefits: [
            "Competitive salary with stock options and performance bonuses",
            "Comprehensive health benefits including medical, dental, and vision",
            "Flexible work arrangements with hybrid options",
            "$12,000 annual professional development budget",
            "401(k) matching with company stock purchase plan",
            "Parental leave and adoption assistance programs",
            "Employee discount on Amazon products and services",
            "Career development programs and internal mobility opportunities",
            "Access to Amazon's cutting-edge technology and resources"
        ],
        skills: ["AWS", "System Architecture", "Microservices", "DevOps", "Scalability", "Security", "Leadership"],
        companyDescription: "Amazon is e-commerce and cloud computing giant delivering innovation to customers globally. We're customer-obsessed and committed to providing the best shopping experience.",
        logo: "/logos/amazon.png",
        featured: false,
        isNew: false,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.4,
        reviews: 1987,
        applicants: 203,
        contactPerson: "Jennifer Martinez",
        contactEmail: "careers@amazon.com",
        contactPhone: "+1 (206) 266-1000",
        companySize: "1,298,000+",
        industry: "E-commerce"
    },
    {
        id: 4,
        title: "Senior iOS Engineer",
        company: "Apple",
        location: "Cupertino, CA",
        type: "Full-time",
        experience: "5+ years",
        salary: "$150k - $200k",
        department: "Engineering",
        workStyle: "On-site",
        postedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        description: "Join Apple's iOS engineering team to create revolutionary mobile experiences. You'll work on products that define the future of mobile technology and impact millions of users worldwide.",
        responsibilities: [
            "Design and develop innovative iOS applications and system frameworks",
            "Optimize iOS performance and user experience for Apple devices",
            "Collaborate with design teams to implement cutting-edge user interfaces",
            "Mentor junior engineers and conduct code reviews",
            "Contribute to iOS architecture and platform evolution",
            "Stay current with mobile development trends and technologies",
            "Ensure security and privacy best practices in iOS development"
        ],
        requirements: [
            "5+ years of experience in iOS development or mobile engineering",
            "Strong proficiency in Swift, Objective-C, and iOS frameworks",
            "Experience with mobile app architecture and design patterns",
            "Understanding of Apple's design principles and human interface guidelines",
            "Experience with performance optimization and debugging",
            "Bachelor's degree in Computer Science or related field",
            "Portfolio of published iOS applications preferred"
        ],
        benefits: [
            "Competitive salary with stock options and performance bonuses",
            "Comprehensive health benefits including medical, dental, and vision",
            "Product discounts on Apple products and services",
            "Generous 401(k) matching and employee stock purchase plan",
            "Parental leave and adoption assistance programs",
            "On-site fitness centers and wellness programs",
            "Professional development opportunities and technical training",
            "Access to Apple's cutting-edge technology and innovation labs"
        ],
        skills: ["Swift", "iOS", "Objective-C", "Xcode", "Mobile Development", "SwiftUI", "Core Data"],
        companyDescription: "Apple is innovative technology company designing revolutionary products and experiences. We create tools that empower people and enrich their lives through beautiful design and intuitive functionality.",
        logo: "/logos/apple.png",
        featured: true,
        isNew: false,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.8,
        reviews: 1543,
        applicants: 267,
        contactPerson: "Lisa Anderson",
        contactEmail: "careers@apple.com",
        contactPhone: "+1 (408) 996-1010",
        companySize: "147,000+",
        industry: "Technology"
    },
    {
        id: 5,
        title: "Cloud Solutions Architect",
        company: "IBM",
        location: "Armonk, NY",
        type: "Full-time",
        experience: "8+ years",
        salary: "$140k - $180k",
        department: "Engineering",
        workStyle: "Remote",
        postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        description: "Lead cloud architecture design for IBM's enterprise solutions. You'll shape the technical direction of hybrid cloud and AI platforms serving global enterprise clients.",
        responsibilities: [
            "Design hybrid cloud architectures combining IBM Cloud and other platforms",
            "Lead technical decisions for enterprise-scale cloud implementations",
            "Architect solutions for AI, analytics, and data workloads",
            "Ensure security, compliance, and governance requirements",
            "Mentor technical teams and establish best practices",
            "Collaborate with sales teams on solution design",
            "Stay current with emerging cloud and enterprise technologies"
        ],
        requirements: [
            "8+ years of experience in cloud architecture or enterprise solutions",
            "Strong experience with IBM Cloud, AWS, Azure, or GCP",
            "Expertise in hybrid cloud and multi-cloud strategies",
            "Knowledge of enterprise security and compliance standards",
            "Experience with containerization and orchestration platforms",
            "Bachelor's degree in Computer Science or related field",
            "IBM certifications or equivalent cloud architecture credentials"
        ],
        benefits: [
            "Competitive salary with performance bonuses and stock options",
            "Comprehensive health benefits including medical and dental",
            "Flexible work arrangements with remote options",
            "$8,000 annual professional development budget",
            "401(k) matching and pension plan",
            "Generous paid time off and holidays",
            "Employee discount on IBM products and services",
            "Career development and internal mobility programs"
        ],
        skills: ["IBM Cloud", "Hybrid Cloud", "Enterprise Architecture", "Security", "DevOps", "AI/ML"],
        companyDescription: "IBM is enterprise technology and consulting company driving digital transformation. We combine industry expertise with innovative technology to help clients solve their most complex challenges.",
        logo: "/logos/ibm.png",
        featured: false,
        isNew: true,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.3,
        reviews: 987,
        applicants: 134,
        contactPerson: "Robert Zhang",
        contactEmail: "careers@ibm.com",
        contactPhone: "+1 (800) 426-4968",
        companySize: "282,100+",
        industry: "Technology"
    },
    {
        id: 6,
        title: "AR/VR Software Engineer",
        company: "Meta",
        location: "Menlo Park, CA",
        type: "Full-time",
        experience: "3-5 years",
        salary: "$130k - $170k",
        department: "Engineering",
        workStyle: "Hybrid",
        postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        description: "Join Meta's AR/VR team to build the future of social connection and immersive experiences. You'll work on cutting-edge technologies that define how people interact in digital worlds.",
        responsibilities: [
            "Develop software and systems for AR/VR hardware and platforms",
            "Create immersive experiences and social features for Meta's products",
            "Optimize performance for real-time rendering and interaction",
            "Collaborate with hardware teams on software-hardware integration",
            "Research and implement new interaction paradigms and user interfaces",
            "Contribute to Meta's open-source initiatives and developer ecosystem",
            "Stay current with emerging AR/VR technologies and standards"
        ],
        requirements: [
            "3-5 years of experience in AR/VR development or related field",
            "Strong programming skills in C++, C#, or similar languages",
            "Experience with game engines (Unity, Unreal) or 3D graphics",
            "Understanding of 3D mathematics, physics, and rendering techniques",
            "Experience with mobile development and cross-platform applications",
            "Knowledge of human-computer interaction and UX design",
            "Bachelor's degree in Computer Science or related field"
        ],
        benefits: [
            "Competitive salary with stock options and performance bonuses",
            "Comprehensive health benefits including mental health coverage",
            "Flexible work arrangements with hybrid options",
            "$10,000 annual professional development budget",
            "401(k) matching and employee stock purchase plan",
            "Unlimited paid time off and sabbatical options",
            "Free meals, snacks, and on-site wellness facilities",
            "Access to cutting-edge AR/VR hardware and research labs"
        ],
        skills: ["C++", "Unity", "Unreal Engine", "3D Graphics", "AR/VR", "Mobile Development", "OpenXR"],
        companyDescription: "Meta is building social connections and the metaverse for global community. We're creating immersive experiences that bring people closer together regardless of physical distance.",
        logo: "/logos/meta.png",
        featured: true,
        isNew: false,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.5,
        reviews: 1876,
        applicants: 189,
        contactPerson: "Dr. Emily Rodriguez",
        contactEmail: "careers@meta.com",
        contactPhone: "+1 (650) 543-4800",
        companySize: "71,970+",
        industry: "Technology"
    },
    {
        id: 7,
        title: "Battery Systems Engineer",
        company: "Tesla",
        location: "Austin, TX",
        type: "Full-time",
        experience: "5+ years",
        salary: "$120k - $160k",
        department: "Engineering",
        workStyle: "On-site",
        postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        description: "Join Tesla's battery engineering team to revolutionize energy storage. You'll work on cutting-edge battery technology that powers electric vehicles and energy solutions worldwide.",
        responsibilities: [
            "Design and develop battery management systems and software",
            "Optimize battery performance, efficiency, and longevity",
            "Collaborate with vehicle engineering teams on integration",
            "Conduct battery testing and validation procedures",
            "Research and implement new battery chemistries and technologies",
            "Ensure safety and compliance with automotive standards",
            "Mentor junior engineers and establish best practices"
        ],
        requirements: [
            "5+ years of experience in battery engineering or related field",
            "Strong knowledge of battery chemistry and electrochemistry",
            "Experience with embedded systems and real-time operating systems",
            "Proficiency in C/C++ and Python for system programming",
            "Understanding of automotive safety standards and regulations",
            "Experience with testing methodologies and quality assurance",
            "Bachelor's degree in Engineering or related field"
        ],
        benefits: [
            "Competitive salary with stock options and performance bonuses",
            "Comprehensive health benefits including medical and dental",
            "Tesla vehicle purchase program and charging credits",
            "401(k) matching and employee stock purchase plan",
            "On-site fitness facilities and wellness programs",
            "Professional development opportunities and technical training",
            "Access to cutting-edge battery research and testing facilities",
            "Employee discount on Tesla products and solar installations"
        ],
        skills: ["Battery Systems", "Embedded Systems", "C/C++", "Python", "Automotive", "Testing", "Safety"],
        companyDescription: "Tesla is accelerating sustainable energy and electric vehicle innovation worldwide. We're building a future where sustainable energy is accessible to everyone through revolutionary products and technology.",
        logo: "/logos/tesla.png",
        featured: false,
        isNew: true,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.6,
        reviews: 1234,
        applicants: 98,
        contactPerson: "Michael Chen",
        contactEmail: "careers@tesla.com",
        contactPhone: "+1 (512) 516-7171",
        companySize: "110,000+",
        industry: "Automotive"
    },
    {
        id: 8,
        title: "Database Administrator",
        company: "Oracle",
        location: "Austin, TX",
        type: "Full-time",
        experience: "3-5 years",
        salary: "$90k - $120k",
        department: "Engineering",
        workStyle: "Remote",
        postedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
        description: "Manage and optimize Oracle database systems for enterprise clients. You'll ensure data integrity, performance, and security for mission-critical business applications.",
        responsibilities: [
            "Install, configure, and maintain Oracle database systems",
            "Monitor database performance and implement optimization strategies",
            "Ensure data backup, recovery, and disaster preparedness",
            "Manage database security and access control",
            "Collaborate with development teams on database design and implementation",
            "Troubleshoot database issues and provide technical support",
            "Stay current with Oracle database features and best practices"
        ],
        requirements: [
            "3-5 years of experience with Oracle database administration",
            "Oracle Certified Professional (OCP) or equivalent certification",
            "Strong knowledge of SQL and database optimization techniques",
            "Experience with database backup and recovery procedures",
            "Understanding of database security and compliance requirements",
            "Experience with database monitoring and performance tuning",
            "Bachelor's degree in Computer Science or related field"
        ],
        benefits: [
            "Competitive salary with performance bonuses and stock options",
            "Comprehensive health benefits including medical and dental",
            "Flexible work arrangements with remote options",
            "$6,000 annual professional development budget",
            "401(k) matching and employee stock purchase plan",
            "Generous paid time off and holidays",
            "Employee discount on Oracle products and training",
            "Career development and internal mobility programs"
        ],
        skills: ["Oracle Database", "SQL", "Database Administration", "Performance Tuning", "Backup & Recovery", "Security"],
        companyDescription: "Oracle is enterprise software company powering business innovation globally. We provide complete cloud applications, platforms, and infrastructure that help organizations innovate and succeed.",
        logo: "/logos/oracle.png",
        featured: false,
        isNew: false,
        isTopMNC: true,
        isFortune500: true,
        isGlobal: true,
        rating: 4.2,
        reviews: 876,
        applicants: 112,
        contactPerson: "David Kim",
        contactEmail: "careers@oracle.com",
        contactPhone: "+1 (650) 506-7000",
        companySize: "143,000+",
        industry: "Technology"
    }
];

export const FILTERS = {
    companies: [
        "Microsoft",
        "Google",
        "Amazon",
        "Apple",
        "IBM",
        "Meta",
        "Tesla",
        "Oracle",
        "Samsung",
        "Intel",
        "Cisco",
        "Adobe"
    ],
    department: [
        "Engineering",
        "Design",
        "Marketing",
        "Sales",
        "HR",
        "Product",
        "Finance",
        "Operations",
        "IT",
        "Consulting"
    ],
    locations: [
        "Redmond, WA",
        "Mountain View, CA",
        "Seattle, WA",
        "Cupertino, CA",
        "Armonk, NY",
        "Menlo Park, CA",
        "Austin, TX",
        "Santa Clara, CA",
        "San Jose, CA",
        "Remote"
    ],
    workStyle: [
        "Remote",
        "Hybrid",
        "On-site"
    ],
    experience: [
        "Entry Level",
        "1-2 years",
        "2-4 years",
        "3-5 years",
        "5+ years"
    ],
    salary: [
        "$70k - $90k",
        "$90k - $110k",
        "$110k - $130k",
        "$130k - $150k",
        "$150k - $170k",
        "$170k+"
    ],
    type: [
        "Full-time",
        "Part-time",
        "Contract",
        "Internship"
    ]
};